# -*- coding: utf-8 -*-
"""日程图 HTML + Pillow 纯渲染。无 nekro 依赖。"""
from __future__ import annotations

import html as html_lib
import io
from typing import Any, Callable, Optional

DEFAULT_VIEWPORT_WIDTH = 560
_PNG_MAGIC = b"\x89PNG"


def escape_html(s: Any) -> str:
    return html_lib.escape("" if s is None else str(s))


def _event_rows(events: list, current_window: str) -> str:
    rows = []
    for ev in events or []:
        window = str(ev.get("window") or "")
        activity = escape_html(ev.get("activity") or "")
        mood = escape_html(ev.get("mood") or "")
        is_current = bool(current_window) and window == current_window
        cls = "event current" if is_current else "event"
        marker = " data-current='1'" if is_current else ""
        rows.append(
            f"<div class='{cls}'{marker}>"
            f"<span class='window'>{escape_html(window)}</span>"
            f"<span class='activity'>{activity}</span>"
            f"<span class='mood'>{mood}</span>"
            f"</div>"
        )
    return "".join(rows)


def _life_card_html(day_card: Optional[dict]) -> str:
    if not day_card:
        return ""
    scene = day_card.get("scene") or {}
    title = escape_html(scene.get("title") or "")
    setting = escape_html(scene.get("setting") or "")
    blurbs = []
    for item in day_card.get("events") or []:
        blurb = escape_html((item or {}).get("blurb") or "")
        if blurb:
            blurbs.append(f"<span class='blurb'>{blurb}</span>")
    blurbs_html = "".join(blurbs)
    scene_line = title
    if setting:
        scene_line = f"{title}<span class='setting'> · {setting}</span>" if title else setting
    return (
        "<div class='life-card'>"
        f"<div class='life-title'>{scene_line}</div>"
        f"<div class='life-blurbs'>{blurbs_html}</div>"
        "</div>"
    )


def build_schedule_html(
    *,
    date_key: str,
    summary: str,
    events: list,
    day_card: Optional[dict] = None,
    current_window: str = "",
) -> str:
    date_s = escape_html(date_key)
    summary_s = escape_html(summary)
    life = _life_card_html(day_card)
    rows = _event_rows(events, current_window)
    w = DEFAULT_VIEWPORT_WIDTH
    return f"""<!doctype html><html><head><meta charset='utf-8'><style>
*{{box-sizing:border-box}}
body{{margin:0;background:#0f1020;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','Noto Sans CJK SC','Microsoft YaHei',sans-serif;color:#2c2440}}
.page{{width:{w}px;padding:26px;background:linear-gradient(160deg,#3b2a63,#1f1740 60%,#120e2c)}}
.card{{border-radius:28px;background:#fbf8ff;box-shadow:0 22px 60px rgba(10,5,40,.45);overflow:hidden}}
.header{{padding:26px 30px 20px;background:linear-gradient(135deg,#6a4bbd,#8a5fd6);color:#fff}}
.title{{font-size:34px;font-weight:800;letter-spacing:.04em}}
.subtitle{{margin-top:6px;font-size:18px;opacity:.92}}
.body{{padding:24px 30px 10px}}
.summary{{padding:14px 16px;border-radius:14px;background:#f1ecfb;color:#5b4f86;font-size:16px;line-height:1.55}}
.life-card{{margin-top:16px;padding:14px 16px;border-radius:16px;background:linear-gradient(135deg,#fff5e9,#ffeede);border:1px solid #f3dcc2}}
.life-title{{font-size:18px;font-weight:800;color:#b9722a}}
.setting{{font-weight:500;font-size:14px;color:#8a6a48}}
.life-blurbs{{margin-top:8px;display:flex;flex-wrap:wrap;gap:8px}}
.blurb{{font-size:13px;padding:2px 10px;border-radius:999px;background:#fff;color:#7a5a38;font-weight:600}}
.flow{{display:flex;flex-direction:column;gap:10px;margin-top:18px}}
.event{{background:#fff;border:1px solid #ece6f5;border-radius:16px;padding:14px 16px;display:flex;flex-wrap:wrap;gap:8px;align-items:center}}
.event.current{{border-color:#8a5fd6;background:#f4eefc;box-shadow:0 0 0 2px rgba(106,75,189,.25)}}
.window{{font-size:14px;font-weight:700;color:#6a4bbd;min-width:108px}}
.activity{{flex:1;font-size:16px;font-weight:700;color:#2c2440}}
.mood{{font-size:13px;color:#8a82a6}}
.footer{{padding:16px 30px 24px;text-align:right;font-size:13px;color:#a99ec6}}
</style></head><body><div class='page'><div class='card'>
<div class='header'>
  <div class='title'>今日日程</div>
  <div class='subtitle'>{date_s}</div>
</div>
<div class='body'>
  <div class='summary'>{summary_s}</div>
  {life}
  <div class='flow'>{rows}</div>
</div>
<div class='footer'>Generated by Nekro Agent</div>
</div></div></body></html>"""


def _load_font(size: int):
    from PIL import ImageFont

    for path in [
        "/usr/share/fonts/truetype/wqy/wqy-microhei.ttc",
        "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]:
        try:
            return ImageFont.truetype(path, size)
        except Exception:
            continue
    return ImageFont.load_default()


def render_fallback_png(
    *,
    date_key: str,
    summary: str,
    events: list,
    day_card: Optional[dict] = None,
) -> bytes:
    from PIL import Image, ImageDraw

    lines = ["今日日程", str(date_key or ""), str(summary or "")]
    if day_card:
        scene = day_card.get("scene") or {}
        title = scene.get("title") or ""
        setting = scene.get("setting") or ""
        if title or setting:
            lines.append(f"{title} {setting}".strip())
        for item in day_card.get("events") or []:
            blurb = (item or {}).get("blurb") or ""
            if blurb:
                lines.append(str(blurb))
    for ev in events or []:
        window = ev.get("window") or ""
        activity = ev.get("activity") or ""
        mood = ev.get("mood") or ""
        lines.append(f"{window}  {activity}  {mood}".strip())

    W, pad, lh = 560, 36, 40
    H = pad * 2 + lh * max(len(lines), 1)
    img = Image.new("RGB", (W, H), (251, 248, 255))
    d = ImageDraw.Draw(img)
    title_font = _load_font(32)
    font = _load_font(22)
    y = pad
    for i, line in enumerate(lines):
        f = title_font if i == 0 else font
        d.text((pad, y), line, font=f, fill=(60, 40, 90) if i == 0 else (70, 60, 90))
        y += lh
    out = io.BytesIO()
    img.save(out, format="PNG")
    return out.getvalue()


async def html_to_image(
    html: str,
    *,
    renderer_url: str,
    timeout: float = 60,
    post: Optional[Callable] = None,
) -> bytes:
    url = renderer_url.rstrip("/") + "/screenshot"
    payload = {
        "html": html,
        "options": {"fullPage": True, "type": "png"},
        "viewport": {
            "width": DEFAULT_VIEWPORT_WIDTH,
            "height": 1200,
            "deviceScaleFactor": 2,
        },
        "gotoOptions": {"waitUntil": "networkidle0", "timeout": 60000},
        "waitForTimeout": 2500,
        "bestAttempt": True,
    }

    if post is None:
        import httpx

        async with httpx.AsyncClient(timeout=timeout, trust_env=False) as client:
            resp = await client.post(url, json=payload)
            resp.raise_for_status()
            data = resp.content
    else:
        resp = await post(url, json=payload, timeout=timeout)
        resp.raise_for_status()
        data = resp.content

    if not data.startswith(_PNG_MAGIC):
        raise RuntimeError("渲染返回无效图片")
    return data


async def render_schedule_card(
    *,
    date_key: str,
    summary: str,
    events: list,
    day_card: Optional[dict] = None,
    current_window: str = "",
    renderer_url: str = "",
    timeout: float = 60,
    post: Optional[Callable] = None,
) -> bytes:
    if renderer_url:
        try:
            html = build_schedule_html(
                date_key=date_key,
                summary=summary,
                events=events,
                day_card=day_card,
                current_window=current_window,
            )
            return await html_to_image(
                html,
                renderer_url=renderer_url,
                timeout=timeout,
                post=post,
            )
        except Exception:
            pass
    return render_fallback_png(
        date_key=date_key,
        summary=summary,
        events=events,
        day_card=day_card,
    )
